---
- hosts: all
  become: true
  tasks:
  - name: install java and docker
    apt:
      name:
      - default-jdk
      - docker.io
      state: present


  - name: start docker service
    service:
      name: docker
      state: started
      enabled: true
      

      
  - name: deploy bootcamp application
    command: docker run -it -d -p 8888:8888 --name bootcampjava sfarzanarazia/hubimages1:bcjava1.0
  handlers:
  - name: run update
    apt:
      update_cache: yes
